var countryData = {
    "Afganistán": "AF",
    "Albania": "AL",
    "Alemania": "DE",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua y Barbuda": "AG",
    "Arabia Saudita": "SA",
    "Argelia": "DZ",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaiyán": "AZ",
    "Bahamas": "BS",
    "Baréin": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Bielorrusia": "BY",
    "Bélgica": "BE",
    "Belice": "BZ",
    "Benín": "BJ",
    "Bután": "BT",
    "Bolivia": "BO",
    "Bosnia y Herzegovina": "BA",
    "Botsuana": "BW",
    "Brasil": "BR",
    "Brunéi": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Camboya": "KH",
    "Camerún": "CM",
    "Canadá": "CA",
    "Catar": "QA",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Chipre": "CY",
    "Colombia": "CO",
    "Comoras": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croacia": "HR",
    "Cuba": "CU",
    "Dinamarca": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Ecuador": "EC",
    "Egipto": "EG",
    "El Salvador": "SV",
    "Guinea Ecuatorial": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Etiopía": "ET",
    "Fiyi": "FJ",
    "Filipinas": "PH",
    "Finlandia": "FI",
    "Francia": "FR",
    "Gabón": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Ghana": "GH",
    "Granada": "GD",
    "Grecia": "GR",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bisáu": "GW",
    "Guyana": "GY",
    "Haití": "HT",
    "Honduras": "HN",
    "Hungría": "HU",
    "Islandia": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Irán": "IR",
    "Iraq": "IQ",
    "Irlanda": "IE",
    "Israel": "IL",
    "Italia": "IT",
    "Jamaica": "JM",
    "Japón": "JP",
    "Jordania": "JO",
    "Kazajistán": "KZ",
    "Kenia": "KE",
    "Kiribati": "KI",
    "Corea del Norte": "KP",
    "Corea del Sur": "KR",
    "Kuwait": "KW",
    "Kirguistán": "KG",
    "Laos": "LA",
    "Letonia": "LV",
    "Líbano": "LB",
    "Lesoto": "LS",
    "Liberia": "LR",
    "Libia": "LY",
    "Liechtenstein": "LI",
    "Lituania": "LT",
    "Luxemburgo": "LU",
    "Macedonia del Norte": "MK",
    "Madagascar": "MG",
    "Malaui": "MW",
    "Malasia": "MY",
    "Maldivas": "MV",
    "Malí": "ML",
    "Malta": "MT",
    "Islas Marshall": "MH",
    "Mauritania": "MR",
    "Mauricio": "MU",
    "México": "MX",
    "Micronesia": "FM",
    "Moldavia": "MD",
    "Mónaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Marruecos": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Países Bajos": "NL",
    "Nueva Zelanda": "NZ",
    "Nicaragua": "NI",
    "Níger": "NE",
    "Nigeria": "NG",
    "Noruega": "NO",
    "Omán": "OM",
    "Pakistán": "PK",
    "Palaos": "PW",
    "Panamá": "PA",
    "Papúa Nueva Guinea": "PG",
    "Paraguay": "PY",
    "Perú": "PE",
    "Filipinas": "PH",
    "Polonia": "PL",
    "Portugal": "PT",
    "Catar": "QA",
    "Rumania": "RO",
    "Rusia": "RU",
    "Ruanda": "RW",
    "San Cristóbal y Nieves": "KN",
    "Santa Lucía": "LC",
    "San Vicente y las Granadinas": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Santo Tomé y Príncipe": "ST",
    "Arabia Saudita": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leona": "SL",
    "Singapur": "SG",
    "Eslovaquia": "SK",
    "Eslovenia": "SI",
    "Islas Salomón": "SB",
    "Somalia": "SO",
    "Sudáfrica": "ZA",
    "España": "ES",
    "Sri Lanka": "LK",
    "Sudán": "SD",
    "Surinam": "SR",
    "Suazilandia": "SZ",
    "Suecia": "SE",
    "Suiza": "CH",
    "Siria": "SY",
    "Tayikistán": "TJ",
    "Tanzania": "TZ",
    "Tailandia": "TH",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad y Tobago": "TT",
    "Túnez": "TN",
    "Turquía": "TR",
    "Turkmenistán": "TM",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ucrania": "UA",
    "Emiratos Árabes Unidos": "AE",
    "Reino Unido": "GB",
    "Estados Unidos": "US",
    "Uruguay": "UY",
    "Uzbekistán": "UZ",
    "Vanuatu": "VU",
    "Ciudad del Vaticano": "VA",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabue": "ZW"
    };

// Obtener el elemento select en el documento
var selectElement = document.getElementById("countrySelect");

// Ordenar los países alfabéticamente
var countries = Object.keys(countryData).sort();

// Agregar las opciones al select
for (var i = 0; i < countries.length; i++) {
    var countryName = countries[i];
    var abbreviation = countryData[countryName];
    var option = document.createElement("option");
    option.value = abbreviation;
    option.textContent = countryName + " (" + abbreviation + ")";
    selectElement.appendChild(option);
}
